---
bots:
  - name: chsbot
    prefix: c?
    max_messages: 10000
    disabled_mentions:
      everyone: false
    token:
      name: CHSBOT_TOKEN
      value:
      env: true
    description: |
      Welcome to CHS Bot! 

      Visit `{bot.command_prefix}help` for a 
      list of commands and how to use them.
      Visit `{bot.command_prefix}about` to 
      see more information about the bot.
    extensions:
      - bot.cogs.core.events
      - bot.cogs.core.info
      - bot.cogs.fun
      - bot.cogs.math
      - bot.cogs.games
      - bot.cogs.voting
      # - bot.cogs.techhounds
      - bot.cogs.embeds
      - bot.cogs.admin
      - bot.cogs.moderation
      # - bot.cogs.modlogs
      # - bot.cogs.mail
    use_default_help_command: false
